apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: mysecret-sops
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:+H6SXtlt033m,iv:Pss0uHCdda9xqACTjFwmTPypnuCJT1Pc18LvucLgAXA=,tag:TH7R6WL5eRiGAAHibzY9LA==,type:str]
          stringData:
            PG_PASSWORD: ENC[AES256_GCM,data:jxvjBFxWNLJCh0GGEvXrApTs0sA=,iv:KqbbU6yrID28n17jVLke9z2fxJGO+WxdGdeUcmF3hRs=,tag:u6TbdaZlmo8yyFhH3C3r9Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19tfqxgdgx3fe96j8fyy0c65nsfj8ku8sl4ccfxnzpn3xpakylg5s8sgac7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0T0J6SmFyUzZZTVBjTXpJ
            dWN6cU9qL3hyU05HNk1WMUVrWWQ1cElsVUdzCjdmR2FjaFVkTHNVbjIweE04dC95
            WVM4NjJDSkppTzV3VmlkUnNvR0FnRlkKLS0tIE1uamYvZWNSVEtRN3hySzAzWTdO
            bm92d01oUHczZ3Bac1NMVm5pbUtKbmsKRoNbsWVECbceaEBHIckgzorJotgHYJM2
            SZsc2GG/qqzRKAdevndXqsdmX5e2UXAKIQHFma0fR6+NN4LC+e0y5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-11T09:29:42Z"
    mac: ENC[AES256_GCM,data:B1Pd5XgkoQNmZgJVGSXYJFcoGMQBBGcXkKS8bVII5prK9dIyY195Efh2iGghxnNq9IY+YbjmUlUzDBllCldFeG5PWiTgxl/aeTx9PN85qHSa1ovo5bzMrz15WkiBUAuDA+YB1YGCEiyCz28hfoKAhjhPzNtNZDnq59jr3Wtd60g=,iv:R7xTqpgO0Yv0dlKOm1oZG7ljTVUN/t/sHCkAhwstn2U=,tag:oR7zt25HqHeb2ARVvxMDHA==,type:str]
    pgp: []
    encrypted_suffix: Templates
    version: 3.9.0
