apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: mysecret-sops2
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:7cs4HQhFfAK/,iv:QUFcjOE2AC6gxP4+sSAbR2S0rcSW0CK7P1WJP5vjxYk=,tag:YHGjrPSVBNxocHdEaiIWhw==,type:str]
          stringData:
            PG_PASSWORD: ENC[AES256_GCM,data:Y275RwhZxw==,iv:k3oi2vnFRYB4XVAthuBtaU5BEWaOaZcmpvI+GilQBUI=,tag:jSxa9Ut/+A4MWKNfuT0XTQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19tfqxgdgx3fe96j8fyy0c65nsfj8ku8sl4ccfxnzpn3xpakylg5s8sgac7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyOGJ5d2w2WnQwT1lDUFBr
            UWwxK1p1YjI4Mkd6cVhFazdiajRSYk96U2hJCm5PU0FPR1o0bWtnNHE4RkVpR29m
            YzZDZWNZRjZ6TkN0dElpU3FHT01RZnMKLS0tIEFMWjF3a1preEhqSWh4NXhRZXRz
            ZVFaMmRCMWVqTFd4TTRvR3FtWENETVEKA2gyQkyTo1cmE+sFTvk130lS4gn2o5Xf
            agDYEWPMdS197wm/a+LJoiEEMJxDe0LS0uLgy2QPgqDMj2PXzxeNjw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-12T08:31:32Z"
    mac: ENC[AES256_GCM,data:atNSjjPu7EiIHhCU+06SAv80cVB78oO5yP2fwzZJcn7eGGSMkKZxQqhPolzB8mktkaQ1QCFHjfcn9DlnMFnPLcSj1+jvflaG3/dFvRqAkdxKhEOPLU18ieopxxbZdD0QwBQ87NF+2moMe6A94gnxyPYWuZyZ7X05zfQkJaaBV+I=,iv:Q0lFsrmEKbXUYQTiqYDwodAXh9INKDLb9liUpqKT/pY=,tag:hveroVs6zrPRhFyoSjb1Fw==,type:str]
    pgp: []
    encrypted_suffix: Templates
    version: 3.9.0
